name: specs

on:
  push:
  pull_request:

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crystal: [latest, nightly]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Run specs
        run: crystal spec
